# Übung Lineare Algebra

## Aufgabe 1 
Lässt sich $\begin{pmatrix} -1 \\ 2 \end{pmatrix}$ als Linearkombination von $\begin{pmatrix} 1 \\ 0 \end{pmatrix}$ und $\begin{pmatrix} 0 \\ 1\end{pmatrix}$ darstellen?
 
Ja, mit den Konstanten $-1$ und $2$ als
 $$
  \begin{pmatrix} -1\\2\end{pmatrix} = -1\begin{pmatrix}1\\0\end{pmatrix} + 2\begin{pmatrix}0\\1\end{pmatrix}.
 $$


## Aufgabe 2
Sind die Vektoren $\begin{pmatrix} 3\\0\\2\end{pmatrix}$, $\begin{pmatrix} 5\\2\\0\end{pmatrix}$, $\begin{pmatrix} 7\\-2\\1\end{pmatrix}$ und $\begin{pmatrix} 8\\0\\0\end{pmatrix}\in\mathbb{R}^3$ linear unabhängig?

Wir müssen dazu testen, ob 

 $$
  a\begin{pmatrix} 3\\0\\2\end{pmatrix} + b\begin{pmatrix} 5\\2\\0\end{pmatrix} + c\begin{pmatrix} 7\\-2\\1\end{pmatrix} + d\begin{pmatrix} 8\\0\\0\end{pmatrix}=\begin{pmatrix}0\\0\\0\end{pmatrix}
 $$
 
 gilt. Das Umstellen dieser Gleichungen liefert uns $b=-2a$, $c=-2a$, $d=\frac{21}{8}a$. Wir können also eine beliebige Zahl für $a$ einsetzen, damit $b,c,d$ berechnen und die Gleichung lösen. Da die Lösung für $a=b=c=d=0$ nicht die einzige Lösung ist, sind die Vektoren nicht linear unabhängig.

## Aufgabe 3
Berechnen Sie für a = $\begin{pmatrix} 2\\4\\-3\end{pmatrix}$, b = $\begin{pmatrix} -1\\5\\0\end{pmatrix}\in\mathbb{R}^3$ folgende Ausdrücke.
 1. $a+b = \begin{pmatrix}2+-1\\4+5\\-3+0\end{pmatrix} = \begin{pmatrix} 1\\9\\-3\end{pmatrix}$,
 2. $2a = \begin{pmatrix}2\cdot 2\\2\cdot 4\\2\cdot -3\end{pmatrix} = \begin{pmatrix}4\\8\\-6\end{pmatrix}$,
 3. $-a  = \begin{pmatrix}-2\\-4\\3\end{pmatrix}$,
 4. $a+\frac{3}{5}b = \begin{pmatrix} 2+\frac{3}{5}\cdot -1\\4+\frac{3}{5}\cdot 5\\-3+\frac{3}{5}\cdot 0\end{pmatrix}= \begin{pmatrix}\frac{7}{5}\\7\\-3\end{pmatrix}$.

## Aufgabe 4
Gegeben sind folgende Gleichungen
 1. $x+3z+t = 15$, 
 2. $3y+7z-t=32$, 
 3. $-2x+y+4z=23$ und 
 4. $x+5y-3z-4t=-19$. 
 
Nutzen Sie den Gauß-Algorithmus um eine Lösung für $x,y,z,t$ zu finden.

### Lösung
 
 Hierzu bringen wir die Gleichungen zuerst in die Form $Ax=b$:
 
 $$
  \begin{pmatrix} 1 & 0 & 3 & 1\\ 0 & 3 & 7 & -1 \\ -2 & 1 & 4 & 0 \\ 1 & 5 & -3 & -4 \end{pmatrix} \begin{pmatrix} x\\y\\z\\t\end{pmatrix} = \begin{pmatrix} 15\\32\\23\\-19 \end{pmatrix}.
 $$
 
 Nun müssen wir aus der vorderen Matrix eine untere Dreiecksmatrix erzeugen. Zuerst erzeugen wir in der ersten Spalte Nullen und erhalten damit
 
 $$
  \begin{pmatrix} 1 & 0 & 3 & 1\\ 0 & 3 & 7 & -1 \\ 0 & 1 & 10 & 2 \\ 0 & 5 & -6 & -5 \end{pmatrix} \begin{pmatrix} x\\y\\z\\t\end{pmatrix} = \begin{pmatrix} 15\\32\\53\\-34 \end{pmatrix}.
 $$
 
 Nun tauschen wir die $3.$ und $2.$ Zeile und erzeugen in der $2.$ Spalte Nullen. Dadurch erhalten wir
 
 $$
  \begin{pmatrix} 1 & 0 & 3 & 1\\ 0 & 1 & 10 & 2 \\ 0 & 0 & -23 & -7 \\ 0 & 0 & -56 & -15 \end{pmatrix} \begin{pmatrix} x\\y\\z\\t\end{pmatrix} = \begin{pmatrix} 15\\32\\-127\\-299 \end{pmatrix}.
 $$
 
 Nun müssen wir nur noch in der letzten Zeile eine Null erzeugen und haben eine untere Dreiecksform:
 
 $$
  \begin{pmatrix} 1 & 0 & 3 & 1\\ 0 & 1 & 10 & 2 \\ 0 & 0 & -23 & -7 \\ 0 & 0 & 0 & \frac{47}{23} \end{pmatrix} \begin{pmatrix} x\\y\\z\\t\end{pmatrix} = \begin{pmatrix} 15\\32\\-127\\\frac{235}{23} \end{pmatrix}.
 $$
 
 Hier können wir nun einfach die Lösungen $t=5$, $z=4$, $y=3$ und $x=-2$ ablesen. Die Probe liefert
 
 $$
  \begin{pmatrix} 1 & 0 & 3 & 1\\ 0 & 3 & 7 & -1 \\ -2 & 1 & 4 & 0 \\ 1 & 5 & -3 & -4 \end{pmatrix} \begin{pmatrix} -2\\3\\4\\5\end{pmatrix} = \begin{pmatrix} 15\\32\\23\\-19 \end{pmatrix}.
 $$

In [1]:
import numpy as np

# Anlegen der beiden Matrizen
xyzt = np.array([[1,0,3,1],[0,3,7,-1],[-2,1,4,0],[1,5,-3,-4]])
r = np.array([15,32,23,-19])

# lösen des Gleichungssystems
s = np.linalg.solve(xyzt, r)

# s beeinhaltet die Lösung
print(s)

# Die Kontrolle liefert uns wie erwartet 0 (beachte die Numerische Ungenauigkeit)
print(xyzt.dot(s)-r)

[-2.  3.  4.  5.]
[1.77635684e-15 7.10542736e-15 0.00000000e+00 3.55271368e-15]


## Aufgabe 5
Sei $a = \begin{pmatrix} 1 \\ 2\\ 3 \end{pmatrix}$ und $b = \begin{pmatrix} 3\\4\\5\end{pmatrix}$. Berechnen Sie.

 1. $a+b = \begin{pmatrix} 1+3 \\ 2+4\\ 3+5 \end{pmatrix} = \begin{pmatrix} 4 \\ 6\\ 8 \end{pmatrix}$
 
 2. $\Vert a\Vert = \sqrt{1^2+2^2+3^2}$
 
 3. $\Vert b-a\Vert = \sqrt{(3-1)^2+(4-2)^2+(5-3)^2} = \sqrt{3\cdot 2^2} = \sqrt {12}$ 
 
 4. $<a,b> = 1\cdot 3+2\cdot 4+5\cdot 3= 3+8+15 = 26$

## Aufgabe 6
Sei $a = \begin{pmatrix} 1\\2\\3                   \end{pmatrix}$, $b = \begin{pmatrix} 2\\1\\1\end{pmatrix}$, $c = \begin{pmatrix} -2\\2\\4  \end{pmatrix}$ und $d = \begin{pmatrix} 1\\4\\2\end{pmatrix}$.
 
 Sind $a,b$ linear unabhängig? Sind $a,b,c$ linear unabhängig? Kann man $d$ als Linearkombination der Vektoren $a,b,c$ darstellen? Geben Sie eine Basis des $\mathbb{R}^3$ an.
 
### Lösung
Um zu testen ob $a,b$ linear unabhängig sind müssen wir schauen ob die folgende Gleichung eine eindeutige Lösung ungleich $0$ hat.
$$
a\cdot \begin{pmatrix} 1\\2\\3 \end{pmatrix} + b\cdot \begin{pmatrix} 2\\1\\1\end{pmatrix} = \begin{pmatrix} 0\\0\\0\end{pmatrix}
$$

Hieraus erhalten wir aus der ersten Zeile $a=-2b$ und aus der zweiten Zeile $a=\frac{b}{2}$. Wir finden also kein $a,b\neq 0$ so dass diese Gleichung aufgeht. Somit sind $a,b$ linear unabhängig.

Um zu schauen ob $a,b,c$ linear unabhängig sind können wir dies auch über den gleichen Ansatz tun.
$$
a\cdot \begin{pmatrix} 1\\2\\3 \end{pmatrix} + b\cdot \begin{pmatrix} 2\\1\\1\end{pmatrix} + c\cdot \begin{pmatrix} -2\\2\\4  \end{pmatrix}= \begin{pmatrix} 0\\0\\0\end{pmatrix}
$$

Wir können dies wie folgt zusammenfassen.
$$
\begin{pmatrix} 1 & 2 & -2\\2 & 1 & 2\\3 & 1 & 4 \end{pmatrix} \begin{pmatrix} a\\b\\c\end{pmatrix} = \begin{pmatrix} 0\\0\\0\end{pmatrix}
$$

Nun können wir diese Matrix in die Dreiecksform bringen (siehe Aufgabe 4).
$$
\begin{pmatrix} 1 & 2 & -2\\0 & -3 & -6\\0 & -5 & 10 \end{pmatrix} \begin{pmatrix} a\\b\\c\end{pmatrix} = 
\begin{pmatrix} 0\\0\\0\end{pmatrix}
\leftrightarrow\begin{pmatrix} 1 & 2 & -2\\0 & -3 & -6\\0 & 0 & 0 \end{pmatrix} \begin{pmatrix} a\\b\\c\end{pmatrix} = 
\begin{pmatrix} 0\\0\\0\end{pmatrix}
$$

Diese Matrix zeigt uns, dass der Rank gleich $2$ ist. Somit sind diese drei Vektoren nicht linear unabhängig. 

Um zu testen ob $d$ eine Linearkombination von $a,b,c$ ist können wir folgende Gleichung aufstellen.

$$
a\cdot \begin{pmatrix} 1\\2\\3 \end{pmatrix} + b\cdot \begin{pmatrix} 2\\1\\1\end{pmatrix} + c\cdot \begin{pmatrix} -2\\2\\4  \end{pmatrix}= \begin{pmatrix} 1\\4\\2\end{pmatrix}
$$

Die Umstellung liefert zwischendurch einen Widerspruch (gerne selbst ausprobieren oder mit https://matrixcalc.org/de testen. Aus diesem Grund ist $d$ nicht als Linearkombination von $a,b,c$ darstellbar.

Eine Basis des $\mathbb{R}^3$ wäre $\begin{pmatrix}1\\0\\0\end{pmatrix}$, $\begin{pmatrix}0\\1\\0\end{pmatrix}$, $\begin{pmatrix}0\\0\\1\end{pmatrix}$. Mit dieser können wir alle beliebige Elemente dieses Raumes darstellen.


## Aufgabe 7
Sei $a = \begin{pmatrix} 4\\2\\-3\end{pmatrix}$ ein Vektor und $A=\begin{pmatrix} 1&1&2\\-3&2& -1\\-1&4&5\end{pmatrix}$ eine Matrix. Berechne und kontrolliere mit Python.
1. $2\cdot A = \begin{pmatrix} 2\cdot 1&2\cdot 1&2\cdot 2\\2\cdot -3&2\cdot 2&2\cdot -1\\2\cdot -1&2\cdot 4&2\cdot 5\end{pmatrix}= \begin{pmatrix} 2&2&4\\-6&4& -2\\-2&8&10\end{pmatrix}$
 
2. $A\cdot a = \begin{pmatrix} 1\cdot 4 + 1\cdot 2 + 2\cdot -3\\-3\cdot 4+ 2\cdot 2 + -1\cdot -3\\-1\cdot 4 + 4\cdot 2 +5\cdot -3\end{pmatrix} = \begin{pmatrix} 0\\-5\\-11\end{pmatrix}$

3. $<-2\cdot A\cdot a, a> = <-2\cdot \begin{pmatrix} 0\\-5\\-11\end{pmatrix}, \begin{pmatrix} 4\\2\\-3\end{pmatrix}> = <\begin{pmatrix} 0\\10\\22\end{pmatrix}, \begin{pmatrix} 4\\2\\-3\end{pmatrix}> = 0\cdot 4 + 10\cdot 2 + 22\cdot -3 = -46$


In [9]:
import numpy as np

# Einlesen der Matrix und des Vektors
A = np.array([[1,1,2],[-3,2,-1],[-1,4,5]])
a = np.array([4,2,-3])

# Teilaufgabe 1
print(2*A)

# Teilaufgabe 2
print(A.dot(a))

# Teilaufgabe 3
print(np.dot(-2*A.dot(a),a))

[[ 2  2  4]
 [-6  4 -2]
 [-2  8 10]]
[  0  -5 -11]
-46


## Aufgabe 8
Schreiben Sie das Gleichungssystem $2x_1 + 3x_2 + x_3 + x_4 = 4$, $5x_1 - x_2 + 3x_3 - x_4 = 0$, $2x_1 - 4x_4 = 8$, $4x_2 - 4x_3 = 8$ in der Form $Ax = b$ und bringen sie die Matrix $A$ in eine Dreiecksform. Lösen Sie danach mit Hilfe der Python Methode `numpy.linalg.solve`.
 


In [2]:
# Eingabe der Matrix A
A = np.array([[2,3,1,1],[5,-1,3,-4],[2,0,0,-4],[0,4,-4,0]])
# Eingabe des Vektors b
b = np.array([4,0,8,8])

# Die Lösung wird in s gespeichert
s = np.linalg.solve(A,b)

# Wir sehen in der Probe, dass das Ergebnis der Differenz 0 ist
np.dot(A,s)-b

array([2.66453526e-15, 0.00000000e+00, 0.00000000e+00, 1.77635684e-15])

## Aufgabe 9
Berechnen Sie den Rang der Matrix in Python. Lerne dazu wie man eine Matrix in Python einliest und finde die richtige Methode.
$$
 A= \begin{pmatrix}
 -150 & -423 & 33 & 99 \\ 
 86 & 820 & 62 & -924 \\ 
 -193 & 295 & -13 & -742 \\ 
 -112 & 152 & -123 & -147 \\ 
 -135 & -160 & -13 & -76
 \end{pmatrix}
$$

In [4]:
# Einlesen der Matrix
A = np.array([[-150,-423,33,99],
              [86,820,62,-924],
              [-193,295,-13,-742],
              [-112,152,-123,-147],
              [-135,-160,-13,-76]])

# Ausrechnen des Ranges. Dieser ist 3.
np.linalg.matrix_rank(A)

3